Repository ChimPlanet/ChimPlanet-front, pull requests merged in 2023-03, with the labels that each got.

#27 refactor: useJobSection replace useState into useReducer
  src/components/Home/JobOfferSection/index.jsx
  src/components/Home/JobOfferSection/jobOfferSectionContent.jsx
  src/hooks/useJobSection.js
Labels: refactor

#29 JobOffer 개선 및 추가 디자인 수정
  src/__mocks__/mock_job_offers.js
  src/components/Home/JobOfferSection/jobOfferSectionContent.jsx
  src/components/JobOffer/index.jsx
  src/components/JobOffer/jobStatusIndicator.jsx
  src/components/JobOffer/jobTypography.jsx
  src/utils/job.js
  src/utils/str.js
Labels: features, fix

#31 Feature/history separate
  src/__mocks__/constants.js
  src/__test__/Header.test.jsx
  src/__test__/Text.test.jsx
  src/__test__/setup.js
  src/api/index.js
  src/components/Header/SearchTab/History/historyList.jsx
  src/components/Header/SearchTab/History/index.jsx
  src/components/Header/SearchTab/index.jsx
  src/components/Header/SearchTab/recommend.jsx
  src/components/Header/SearchTab/recommendTagSection.jsx
  src/constants/index.js
  src/hooks/useHistory.js
  src/hooks/useTagSearch.js
  src/hooks/useTagTrie.js
  src/utils/Context/historyContext.js
Labels: features, refactor

#34 메인 화면 프로토타입 1차
  src/App.jsx
  src/__mocks__/mock_job_offers.js
  src/api/banner/fetchSubBanner.js
  src/api/job/fetchOfficialOffer.js
  src/api/job/fetchPopularOffer.js
  src/api/job/fetchRecentOffer.js
  src/assets/default_thumbnail.png
  src/components/AppRoutes.jsx
  src/components/BookmarkSection.jsx
  src/components/Header/HeaderTab/menuBar.jsx
  src/components/Home/HomeCarousel/index.jsx
  src/components/Home/JobOfferSection/jobOfferSectionContent.jsx
  src/components/Home/MoreOfferButton.jsx
  src/components/Home/Sections/OfficialSection.jsx
  src/components/Home/Sections/PopularSection.jsx
  src/components/Home/Sections/RecentSection.jsx
  src/components/Home/SubBanner/index.jsx
  src/components/JobOffer/index.jsx
  src/components/JobOffer/jobOfferMapContent.jsx
  src/components/JobOffer/jobOfferThumbnail.jsx
  src/components/JobOfferSection/index.jsx
  src/components/JobOfferSection/jobOfferSectionContent.jsx
  src/components/JobOfferSection/jobOfferSectionHeader.jsx
  src/components/Loading.jsx
  src/components/icons/ArrowBelowIcon.jsx
  src/constants/query.js
  src/constants/route.js
  src/hooks/useJobSection.js
  src/pages/About.jsx
  src/pages/Event.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
  src/pages/Official.jsx
  src/query/banner.js
  src/query/job.js
  src/styles/App.scss
  src/utils/job.js
Labels: features, refactor

#35 디자인 세부 요소 반영
  src/App.jsx
  src/__mocks__/mock_job_offers.js
  src/components/Header/CategoryOverlay/index.jsx
  src/components/Header/HeaderTab/menuBar.jsx
  src/components/Header/SearchTab/index.jsx
  src/components/Header/index.jsx
  src/components/Home/HomeCarousel/Carousel/carouselHooks.js
  src/components/Home/HomeCarousel/index.jsx
  src/components/Home/Sections/OfficialSection.jsx
  src/components/Home/Sections/PopularSection.jsx
  src/components/Home/Sections/RecentSection.jsx
  src/components/Home/SubBanner/index.jsx
  src/components/JobOffer/JobOfferSection/index.jsx
  src/components/JobOffer/JobOfferSection/jobOfferSectionContent.jsx
  src/components/JobOffer/JobOfferSection/jobOfferSectionHeader.jsx
  src/components/JobOffer/index.jsx
  src/components/JobOffer/jobOfferThumbnail.jsx
  src/components/Text/index.jsx
  src/components/icons/MenuIcon.jsx
  src/styles/App.scss
Labels: features, fix

#36 세부 디자인 수정사항 반영
  src/components/Home/MoreOfferButton.jsx
  src/components/Home/Sections/RecentSection.jsx
  src/components/JobOffer/JobOfferSection/index.jsx
  src/components/JobOffer/JobOfferSection/jobOfferSectionContent.jsx
  src/components/JobOffer/jobStatusIndicator.jsx
  src/components/JobOffer/jobTypography.jsx
  src/hooks/useJobSection.js
Labels: features, refactor

#41 feature: Add Category Overlay UI(#10)
  src/components/Header/CategoryOverlay/childCategoryColumn.jsx
  src/components/Header/CategoryOverlay/index.jsx
  src/components/Header/CategoryOverlay/parentCategoryColumn.jsx
  src/components/Header/HeaderTab/menuBar.jsx
Labels: features

#42 Feature/combine detail
  cypress.config.js
  cypress/e2e/home/gnb.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  index.html
  package.json
  src/App.jsx
  src/__mocks__/mock_job_detail.js
  src/__test__/Header.test.jsx
  src/api/job/fetchJobOfferDetail.js
  src/api/job/fetchRecentOffer.js
  src/components/FloatingMenu.jsx
  src/components/Header/CategoryOverlay/childCategoryColumn.jsx
  src/components/Header/CategoryOverlay/index.jsx
  src/components/Header/CategoryOverlay/parentCategoryColumn.jsx
  src/components/Header/HeaderTab/menuBar.jsx
  src/components/Header/SearchTab/index.jsx
  src/components/Header/SearchTab/realSearchBar.jsx
  src/components/Header/index.jsx
  src/components/Home/Sections/OfficialSection.jsx
  src/components/Home/Sections/PopularSection.jsx
  src/components/Home/Sections/RecentSection.jsx
  src/components/JobOffer/JobDetailSubscriber/PostTag.jsx
  src/components/JobOffer/JobDetailSubscriber/index.jsx
  src/components/JobOffer/JobDetailSubscriber/jobDetailContent.jsx
  src/components/JobOffer/JobDetailSubscriber/jobDetailHeader.jsx
  src/components/JobOffer/JobDetailSubscriber/jobDetailMenuBar.jsx
  src/components/JobOffer/JobOfferSection/index.jsx
  src/components/JobOffer/JobOfferSection/jobOfferSectionContent.jsx
  src/components/JobOffer/index.jsx
  src/components/JobOffer/jobOfferMapContent.jsx
  src/components/JobOffer/jobOfferThumbnail.jsx
  src/components/JobOffer/jobTypography.jsx
  src/components/PostDetail/DetailMenuBar.jsx
  src/components/PostDetail/DetailPostHeader.jsx
  src/components/PostDetail/index.jsx
  src/components/Search/NoResultFound.jsx
  src/components/Search/SearchResult.jsx
  src/components/Theme.jsx
  src/constants/route.js
  src/context/articleContext.jsx
  src/context/index.jsx
  src/context/themeContext.jsx
  src/hooks/useSearch.js
  src/hooks/useTagSearch.js
  src/main.jsx
  src/pages/AppRoutes.jsx
  src/pages/Search.jsx
  src/query/job.js
  src/utils/job.js
  yarn.lock
Labels: features, refactor, chore

#43 fix: 카테고리 호버 후 다른 메뉴 이동시, 카테고리가 사라지지 않는 버그
  src/components/Header/HeaderTab/menuBar.jsx
  src/hooks/useTimer.js
Labels: bug, fix

#44 feature: 디자인변경, 무한스크롤(#22)
  src/components/JobInfiniteScroll/index.jsx
  src/components/JobNavBar/index.jsx
  src/pages/Job.jsx
Labels: features

#45 feature: Add Design To Detail Modal
  src/components/JobOffer/JobDetailSubscriber/index.jsx
  src/components/JobOffer/JobDetailSubscriber/jobDetailContent.jsx
Labels: chore

#46 feature: Banner, Job 관련 Skeleton 추가
  src/api/banner/fetchBanner.js
  src/components/Home/HomeCarousel/index.jsx
  src/components/JobOffer/JobOfferSection/index.jsx
  src/components/JobOffer/JobOfferSection/jobOfferSectionContent.jsx
  src/components/Skeletons/BannerSkeleton.jsx
  src/components/Skeletons/JobOfferSkeleton.jsx
  src/components/Skeletons/JobSectionSkeleton.jsx
Labels: features

#48 fix: 상세보기 모달 동작 및 디자인 수정(#47)
  src/api/job/fetchJobOfferDetail.js
  src/components/JobOffer/JobDetailSubscriber/index.jsx
  src/components/JobOffer/JobDetailSubscriber/jobDetailContent.jsx
  src/components/JobOffer/JobDetailSubscriber/jobDetailMenuBar.jsx
  src/components/Loading.jsx
Labels: features, fix

#49 fix: 카테고리 검색 타입 undefined 문제
  src/components/Header/CategoryOverlay/childCategoryColumn.jsx
  src/components/Header/CategoryOverlay/parentCategoryColumn.jsx
  src/components/Search/InvalidSearch.jsx
  src/components/Search/SearchResult.jsx
  src/hooks/useSearch.js
  src/pages/Search.jsx
Labels: fix

#50 Page/admin
  .husky/husky-config/pre-push
  package.json
  src/App.jsx
  src/__mocks__/mock_job_offers.js
  src/common/components/FloatingMenu.jsx
  src/common/components/ResizableGrid.jsx
  src/common/components/Sidebar/components/Sidebar.jsx
  src/common/components/Sidebar/components/SidebarGroup.jsx
  src/common/components/Sidebar/components/SidebarGroupItem.jsx
  src/common/components/Sidebar/index.js
  src/common/icons/ArrowBelowSmallIcon.jsx
  src/common/icons/DashboardIcon.jsx
  src/common/icons/NotificationIcon.jsx
  src/common/icons/PopupIcon.jsx
  src/common/icons/UlIcon.jsx
  src/common/icons/UserIcon.jsx
  src/common/icons/index.js
  src/components/JobView/JobViewContext.js
  src/components/JobView/api/model.js
  src/components/JobView/api/query.js
  src/components/JobView/components/JobView.jsx
  src/components/JobView/components/JobViewContent.jsx
  src/components/JobView/components/JobViewHeader.jsx
  src/components/JobView/components/JobViewHeaderCondition.jsx
  src/components/JobView/components/JobViewHeaderOrderByButton.jsx
  src/components/JobView/components/JobViewHeaderQuery.jsx
  src/components/JobView/index.js
  src/components/Search/SearchResult.jsx
  src/components/admin/AdminDashboard.jsx
  src/components/admin/AdminSidebar.jsx
  src/constants/route.js
  src/pages/AdminContents.jsx
  src/pages/AdminDashboard.jsx
  src/pages/AdminMarketing.jsx
  src/pages/AdminOutlet.jsx
  src/pages/AppRoutes.jsx
  src/pages/ClientOutlet.jsx
  src/pages/Home.jsx
  src/pages/Search.jsx
  src/routes/AppRoutes.jsx
  src/utils/job.js
  yarn.lock
Labels: features

#51 Feature/detail modal
  src/components/JobDetailSubscriber/jobDetailMenuBar.jsx
  src/components/JobInfiniteScroll/index.jsx
  src/pages/Job.jsx
  src/routes/AppRoutes.jsx
Labels: features

#54 fix: Fix Admin Component Lazy Import Statement(#11)
  src/common/components/Sidebar/components/SidebarGroup.jsx
  src/common/components/Sidebar/components/SidebarGroupItem.jsx
  src/components/admin/AdminSidebar.jsx
  src/pages/AdminOutlet.jsx
  src/routes/AppRoutes.jsx
Labels: fix

#55 관리자 페이지 기초 레이아웃 추가
  src/common/components/Sidebar/components/SidebarGroupItem.jsx
  src/components/JobView/components/JobViewHeaderOrderByButton.jsx
  src/components/JobView/components/JobViewHeaderQuery.jsx
  src/components/admin/AdminSidebar.jsx
  src/pages/AdminOutlet.jsx
Labels: features, fix

#59 features: API에 맞게 수정(#14)
  src/components/JobInfiniteScroll/index.jsx
  src/pages/Job.jsx
Labels: features

#60 API Endpoint Decorator & Class 추가
  src/components/Home/Sections/OfficialSection.jsx
  src/components/Home/Sections/PopularSection.jsx
  src/components/Home/Sections/RecentSection.jsx
  src/components/JobDetailSubscriber/jobDetailContent.jsx
  src/query/banner.js
  src/query/offer.js
  src/service/backend/banner-client.js
  src/service/backend/http-client.js
  src/service/backend/index.js
  src/service/backend/offer-client.js
  src/service/domain.decorator.js
  src/service/offer/offer-content.js
  src/service/offer/offer.api.js
Labels: features, refactor

#63 fix: Fix(#14)
  src/pages/Job.jsx
  src/query/offer.js
Labels: fix

#65 feat: admin contents layout(#64)
  src/components/admin/Contents/__mocks__/pseudoOffers.js
  src/components/admin/Contents/components/ContentsHeader.jsx
  src/components/admin/Contents/components/ContentsOfferSection.jsx
  src/components/admin/Contents/components/ContentsSearch.jsx
  src/components/admin/Contents/components/ContentsTab.jsx
  src/components/admin/Contents/index.js
  src/pages/AdminContents.jsx
  src/pages/AdminDashboard.jsx
  src/pages/AdminMarketing.jsx
  src/pages/AdminOutlet.jsx
Labels: features

#66 fix: 오타수정(#64)
  src/components/admin/Contents/components/ContentsTab.jsx
Labels: fix
