Repository ChimPlanet/ChimPlanet-front, pull requests merged in 2023-04, with the labels that each got.

#69 Feature/configurable banner
  package.json
  src/__mocks__/mock_job_offers.js
  src/components/Home/SubBanner/index.jsx
  src/components/admin/Marketing/__mocks__/pseudoOffers.js
  src/components/admin/Marketing/components/BannerSequenceForm/components/BannerSequenceDragItem.jsx
  src/components/admin/Marketing/components/BannerSequenceForm/components/BannerSequenceForm.jsx
  src/components/admin/Marketing/components/BannerSequenceForm/components/BannerSequenceForm.style.js
  src/components/admin/Marketing/components/BannerSequenceForm/index.js
  src/components/admin/Marketing/components/ConfigurableBanner.jsx
  src/components/admin/Marketing/components/ConfigurableMainLayout.style.js
  src/components/admin/Marketing/components/ConfigurationRegisterOptionMenu.jsx
  src/components/admin/Marketing/components/ConfigurationSequenceOptionMenu.jsx
  src/components/admin/Marketing/components/ConfigurationSequenceOptionMenu.style.js
  src/components/admin/Marketing/components/utils/index.js
  src/context/preloadContext.jsx
  src/context/sizeTypeContext.jsx
  src/pages/ClientOutlet.jsx
  src/query/banner.js
  src/service/backend/banner-client.js
  src/service/banner/banner-utils.js
  src/service/banner/fetchBanner.js
  src/service/banner/fetchSubBanner.js
  src/service/offer/offers.js
  yarn.lock
Labels: features, fix

#70 배너 순서 변경 기능 추가
  blueprint.drawio
  src/__mocks__/mock_job_offers.js
  src/common/components/ErrorBoundary.jsx
  src/common/components/VerticalDraggableList/VerticalDraggableList.jsx
  src/common/components/VerticalDraggableList/index.js
  src/common/icons/DoubleSlashIcon.jsx
  src/common/icons/TrashCanIcon.jsx
  src/common/icons/index.js
  src/components/Banner/Banner.jsx
  src/components/Banner/Banner.style.js
  src/components/Banner/index.js
  src/components/Banner/index.jsx
  src/components/admin/Marketing/components/BannerPreviewList.style.js
  src/components/admin/Marketing/components/BannerSequenceForm/components/BannerSequenceDragItem.jsx
  src/components/admin/Marketing/components/BannerSequenceForm/components/BannerSequenceDragItem.style.js
  src/components/admin/Marketing/components/BannerSequenceForm/components/BannerSequenceForm.jsx
  src/components/admin/Marketing/components/BannerSequenceForm/components/BannerSequenceForm.style.js
  src/components/admin/Marketing/components/BannerSequenceForm/hooks/useBannerSequenceForm.js
  src/components/admin/Marketing/components/BannerSequenceForm/utils/index.js
  src/components/admin/Marketing/components/ConfigurableBanner.jsx
  src/components/admin/Marketing/components/ConfigurableSidebarMenu.jsx
  src/components/admin/Marketing/components/ConfigurationRegisterOptionMenu.jsx
  src/components/admin/Marketing/components/ConfigurationRegisterOptionMenu.style.js
  src/components/admin/Marketing/components/ConfigurationSequenceOptionMenu.jsx
  src/components/admin/Marketing/components/ConfigurationSequenceOptionMenu.style.js
  src/context/preloadContext.jsx
  src/main.jsx
  src/pages/ClientOutlet.jsx
  src/service/backend/banner-client.js
  src/service/backend/offer-client.js
  src/service/banner/banner-request.js
  src/service/banner/banner-utils.js
Labels: features, refactor

#71 Feature/post management
  package.json
  src/App.jsx
  src/atoms/ContentManagement.js
  src/common/icons/DetailedSettingsIcon.jsx
  src/common/icons/MinXIcon.jsx
  src/common/icons/PreviewIcon.jsx
  src/common/icons/index.js
  src/components/admin/Contents/__mocks__/mock_Content_job_detail.js
  src/components/admin/Contents/components/ContentOfferSubscriber/ContentOfferDetail.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/ContentOfferHeader.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/ContentOfferSidebar.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/index.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ContentSetting.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ContentSettingBody.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ContentSettingCategory.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ContentSettingHeader.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ContentSettingTag.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ImageUploadBox.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/util.js
  src/components/admin/Contents/components/ContentsHeader.jsx
  src/components/admin/Contents/components/ContentsOfferSection.jsx
  src/components/admin/Contents/components/ContentsSearch.jsx
  src/components/admin/Contents/components/JobOffer/ContentJobOffer.jsx
  src/components/admin/Contents/components/JobOffer/ContentJobOfferThumbnail.jsx
  src/components/admin/Contents/components/JobOffer/ContentJobStatusIndicator.jsx
  src/components/admin/Contents/components/JobOffer/ContentJobTypography.jsx
  src/components/admin/Contents/components/JobOffer/ContentMapJobOffer.jsx
  src/components/admin/Contents/components/post/ContentsOfferSection.jsx
  src/components/admin/Contents/components/post/ContentsTab.jsx
  src/components/admin/Contents/components/post/index.jsx
  src/components/admin/Contents/components/tag/index.jsx
  src/components/admin/Contents/index.js
  src/pages/AdminContents.jsx
  src/pages/Job.jsx
  src/query/tag.js
  src/service/backend/index.js
  src/service/backend/tag-client.js
  src/service/tag/index.js
  src/service/tag/tag.preprocess.js
  src/service/tag/tags.js
  yarn.lock
Labels: features

#72 feat: api 적용(#22)
  src/atoms/PostList.js
  src/common/components/JobOffer/components/jobOfferThumbnail.jsx
  src/components/JobInfiniteScroll/index.jsx
  src/components/JobNavBar/index.jsx
  src/pages/Job.jsx
  src/query/offer.js
  src/service/backend/offer-client.js
  src/service/offer/offer.preprocess.js
Labels: features

#73 fix: 버그 수정(#64)
  src/components/admin/Contents/components/post/index.jsx
Labels: bug, fix

#74 docs: console제거(#22)
  src/common/components/JobOffer/components/jobOfferThumbnail.jsx
  src/components/JobInfiniteScroll/index.jsx
Labels: wontfix

#75 feat: add tag, category(#64)
  src/components/admin/Contents/components/ContentOfferSubscriber/ContentOfferDetail.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/index.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ContentSettingBody.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ContentSettingCategory.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ContentSettingTag.jsx
  src/components/admin/Contents/components/JobOffer/ContentMapJobOffer.jsx
  src/components/admin/Contents/components/post/ContentsOfferSection.jsx
  src/components/admin/Contents/components/post/index.jsx
Labels: features

#78 Feature/job page
  src/common/icons/CircleIcon.jsx
  src/common/icons/DetailBookMark.jsx
  src/common/icons/LineIcon.jsx
  src/common/icons/MobileBookMarkIcon.jsx
  src/common/icons/MobileCafeIcon.jsx
  src/common/icons/MobileShareIcon.jsx
  src/common/icons/ProfileIcon.jsx
  src/common/icons/ThreeDotIcon.jsx
  src/common/icons/index.js
  src/components/JobDetailSubscriber/PostTag.jsx
  src/components/JobDetailSubscriber/index.jsx
  src/components/JobDetailSubscriber/jobDetailContent.jsx
  src/components/JobDetailSubscriber/jobDetailHeader.jsx
  src/components/JobDetailSubscriber/jobDetailMenuBar.jsx
  src/components/JobDetailSubscriber/jobDetailMobileMenuBar.jsx
  src/components/JobInfiniteScroll/index.jsx
  src/components/JobNavBar/index.jsx
  src/components/admin/Contents/components/ContentsHeader.jsx
  src/components/admin/Contents/components/post/ContentsOfferSection.jsx
  src/components/admin/Contents/components/post/ContentsTab.jsx
  src/pages/AdminContents.jsx
  src/pages/Job.jsx
  src/service/offer/offer-content.js
Labels: features

#80 feat: page layout(#79)
  src/components/Home/Sections/EventSection.jsx
  src/pages/ClientOutlet.jsx
  src/pages/Event.jsx
  src/service/backend/offer-client.js
Labels: features

#82 feat: add layout(#81)
  package.json
  src/components/Home/Sections/FixMemberSection.jsx
  src/components/Home/Sections/IsegyeSection.jsx
  src/pages/Official.jsx
  yarn.lock
Labels: features

#83 feat: addCategory addTag adminPage(#64)
  src/components/admin/Contents/__mocks__/mock_Content_job_detail.js
  src/components/admin/Contents/__mocks__/pseudoOffers.js
  src/components/admin/Contents/components/Category/Category.jsx
  src/components/admin/Contents/components/Category/components/Menubar.jsx
  src/components/admin/Contents/components/Category/components/PseudoBanner.jsx
  src/components/admin/Contents/components/Category/components/PseudoHomeHeader.jsx
  src/components/admin/Contents/components/Category/components/PseudoOfferSection.jsx
  src/components/admin/Contents/components/ContentOfferSubscriber/settingModal/ContentSettingCategory.jsx
  src/components/admin/Contents/components/ContentsHeader.jsx
  src/components/admin/Contents/components/index.js
  src/components/admin/Contents/components/post/index.jsx
  src/components/admin/Contents/components/tag/AddTag/AddTagBody.jsx
  src/components/admin/Contents/components/tag/AddTag/AddTagFooter.jsx
  src/components/admin/Contents/components/tag/AddTag/AddTagHeader.jsx
  src/components/admin/Contents/components/tag/AddTag/AddTagModal.jsx
  src/components/admin/Contents/components/tag/AddTag/index.js
  src/components/admin/Contents/components/tag/TagTab.jsx
  src/components/admin/Contents/components/tag/index.jsx
  src/pages/AdminContents.jsx
  src/service/backend/tag-client.js
Labels: features

#85 feat: Search API 연동
  package.json
  src/App.jsx
  src/common/components/JobOffer/components/jobOfferSectionContent.jsx
  src/common/components/Sidebar/components/Sidebar.jsx
  src/common/components/Sidebar/components/SidebarGroup.jsx
  src/common/components/Sidebar/components/SidebarGroupItem.jsx
  src/common/components/Sidebar/index.js
  src/common/icons/ChimplanetNotFoundIcon.jsx
  src/common/icons/index.js
  src/components/BookmarkSection.jsx
  src/components/Header/components/CategoryOverlay/childCategoryColumn.jsx
  src/components/Header/components/CategoryOverlay/index.jsx
  src/components/Header/components/CategoryOverlay/parentCategoryColumn.jsx
  src/components/Header/components/Header.jsx
  src/components/JobView/JobViewContext.js
  src/components/JobView/components/JobViewContent.jsx
  src/components/JobView/components/JobViewContentNotFound.jsx
  src/components/MobileMenu/components/CategoryLinkAccordion.jsx
  src/components/MobileMenu/components/MobileMenu.jsx
  src/components/MobileMenu/index.js
  src/context/index.jsx
  src/context/preloadContext.jsx
  src/main.jsx
  src/service/backend/offer-client.js
  src/service/banner/banner-utils.js
  src/service/tag/tags.js
  src/utils/index.js
  yarn.lock
Labels: features
